sudo: false

language: c

matrix:
  include:
    - env: GHCVER=8.4.1 CABALVER=head
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.4.1
            - cabal-install-head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - CABAL_OPTS=""
  - |
    case "$GHCVER" in
    head )
      CABAL_OPTS="$CABAL_OPTS --allow-newer"
      ;;
    esac
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - cabal install --enable-tests --only-dep $CABAL_OPTS

script:
  - cabal configure --enable-tests --ghc-options=-Werror $CABAL_OPTS && cabal build && cabal test
